import { Octokit } from '@octokit/rest'

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })
const org = process.env.GITHUB_ORG!

export async function createGitHubRepo(repoName: string): Promise<string> {
  console.log(`[github] creating repo: ${org}/${repoName}`)

  try {
    await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      private: false,
      auto_init: true,
      description: 'Preorder sample site — generated by Preorder Site Generator',
    })
    // Wait for GitHub to initialise the repo before we try to push
    await sleep(3000)
    console.log(`[github] repo created: ${repoName}`)
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    if (msg.includes('already exists')) {
      console.log(`[github] repo already exists, reusing: ${repoName}`)
    } else {
      throw new Error(`Repository creation failed.: ${msg}`)
    }
  }

  return `https://github.com/${org}/${repoName}`
}

/**
 * Push all files to a repo in a single atomic commit using the Git Trees API.
 * This avoids SHA race conditions that happen with parallel per-file updates.
 */
export async function pushFilesToRepo(
  repoName: string,
  files: Record<string, string | Buffer>
): Promise<void> {
  console.log(`[github] pushing ${Object.keys(files).length} files to ${repoName} via tree API`)

  // 1. Get the default branch's latest commit SHA
  const { data: refData } = await octokit.git.getRef({
    owner: org,
    repo: repoName,
    ref: 'heads/main',
  })
  const latestCommitSha = refData.object.sha

  // 2. Get the tree SHA of that commit
  const { data: commitData } = await octokit.git.getCommit({
    owner: org,
    repo: repoName,
    commit_sha: latestCommitSha,
  })
  const baseTreeSha = commitData.tree.sha

  // 3. Create blobs for each file
  const treeItems = await Promise.all(
    Object.entries(files).map(async ([filePath, content]) => {
      const isBuffer = Buffer.isBuffer(content)
      const { data: blob } = await octokit.git.createBlob({
        owner: org,
        repo: repoName,
        content: isBuffer
          ? (content as Buffer).toString('base64')
          : Buffer.from(content as string).toString('base64'),
        encoding: 'base64',
      })
      return {
        path: filePath,
        mode: '100644' as const,
        type: 'blob' as const,
        sha: blob.sha,
      }
    })
  )

  // 4. Create a new tree on top of the base tree
  const { data: newTree } = await octokit.git.createTree({
    owner: org,
    repo: repoName,
    base_tree: baseTreeSha,
    tree: treeItems,
  })

  // 5. Create a commit pointing to the new tree
  const { data: newCommit } = await octokit.git.createCommit({
    owner: org,
    repo: repoName,
    message: 'Add generated preorder site files',
    tree: newTree.sha,
    parents: [latestCommitSha],
  })

  // 6. Update the branch ref to point to the new commit
  await octokit.git.updateRef({
    owner: org,
    repo: repoName,
    ref: 'heads/main',
    sha: newCommit.sha,
  })

  console.log(`[github] pushed all files to ${repoName} (commit: ${newCommit.sha})`)
}

const MAIN_REPO = process.env.GITHUB_MAIN_REPO!

/**
 * Read a file from the main app repo. Returns null if not found.
 */
export async function readMainRepoFile(filePath: string): Promise<string | null> {
  try {
    const { data } = await octokit.repos.getContent({ owner: org, repo: MAIN_REPO, path: filePath })
    if (Array.isArray(data) || data.type !== 'file') return null
    return Buffer.from(data.content, 'base64').toString('utf-8')
  } catch {
    return null
  }
}

/**
 * Write (create or update) a file in the main app repo.
 */
export async function writeMainRepoFile(filePath: string, content: string, message: string): Promise<void> {
  let existingSha: string | undefined
  try {
    const { data } = await octokit.repos.getContent({ owner: org, repo: MAIN_REPO, path: filePath })
    if (!Array.isArray(data) && data.type === 'file') existingSha = data.sha
  } catch { /* file doesn't exist yet */ }

  await octokit.repos.createOrUpdateFileContents({
    owner: org,
    repo: MAIN_REPO,
    path: filePath,
    message,
    content: Buffer.from(content).toString('base64'),
    ...(existingSha ? { sha: existingSha } : {}),
  })
}

export async function deleteGitHubRepo(repoName: string): Promise<void> {
  console.log(`[github] deleting repo: ${org}/${repoName}`)
  await octokit.repos.delete({ owner: org, repo: repoName })
  console.log(`[github] deleted repo: ${repoName}`)
}

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms))
}
